/*
 * generated by Xtext 2.26.0
 */
package cuestionario.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import cuestionario.ide.contentassist.antlr.internal.InternalCuestionarioParser;
import cuestionario.services.CuestionarioGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class CuestionarioParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(CuestionarioGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, CuestionarioGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getPreguntaAccess().getAlternatives(), "rule__Pregunta__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEDoubleAccess().getAlternatives_4_0(), "rule__EDouble__Alternatives_4_0");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getCuestionarioAccess().getGroup(), "rule__Cuestionario__Group__0");
			builder.put(grammarAccess.getCuestionarioAccess().getGroup_3(), "rule__Cuestionario__Group_3__0");
			builder.put(grammarAccess.getCuestionarioAccess().getGroup_6(), "rule__Cuestionario__Group_6__0");
			builder.put(grammarAccess.getCuestionarioAccess().getGroup_11(), "rule__Cuestionario__Group_11__0");
			builder.put(grammarAccess.getCategoriaAccess().getGroup(), "rule__Categoria__Group__0");
			builder.put(grammarAccess.getCategoriaAccess().getGroup_5(), "rule__Categoria__Group_5__0");
			builder.put(grammarAccess.getCategoriaAccess().getGroup_5_2(), "rule__Categoria__Group_5_2__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup(), "rule__EDouble__Group__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup_4(), "rule__EDouble__Group_4__0");
			builder.put(grammarAccess.getPreguntaUnicaAccess().getGroup(), "rule__PreguntaUnica__Group__0");
			builder.put(grammarAccess.getPreguntaUnicaAccess().getGroup_8(), "rule__PreguntaUnica__Group_8__0");
			builder.put(grammarAccess.getPreguntaUnicaAccess().getGroup_18(), "rule__PreguntaUnica__Group_18__0");
			builder.put(grammarAccess.getPreguntaUnicaAccess().getGroup_18_2(), "rule__PreguntaUnica__Group_18_2__0");
			builder.put(grammarAccess.getPreguntaUnicaAccess().getGroup_18_4(), "rule__PreguntaUnica__Group_18_4__0");
			builder.put(grammarAccess.getPreguntaMultipleAccess().getGroup(), "rule__PreguntaMultiple__Group__0");
			builder.put(grammarAccess.getPreguntaMultipleAccess().getGroup_8(), "rule__PreguntaMultiple__Group_8__0");
			builder.put(grammarAccess.getPreguntaMultipleAccess().getGroup_16(), "rule__PreguntaMultiple__Group_16__0");
			builder.put(grammarAccess.getPreguntaMultipleAccess().getGroup_16_2(), "rule__PreguntaMultiple__Group_16_2__0");
			builder.put(grammarAccess.getPreguntaMultipleAccess().getGroup_17(), "rule__PreguntaMultiple__Group_17__0");
			builder.put(grammarAccess.getPreguntaMultipleAccess().getGroup_17_2(), "rule__PreguntaMultiple__Group_17_2__0");
			builder.put(grammarAccess.getPreguntaMultipleAccess().getGroup_17_4(), "rule__PreguntaMultiple__Group_17_4__0");
			builder.put(grammarAccess.getRespuestaAccess().getGroup(), "rule__Respuesta__Group__0");
			builder.put(grammarAccess.getCuestionarioAccess().getPreguntasAssignment_2(), "rule__Cuestionario__PreguntasAssignment_2");
			builder.put(grammarAccess.getCuestionarioAccess().getPreguntasAssignment_3_1(), "rule__Cuestionario__PreguntasAssignment_3_1");
			builder.put(grammarAccess.getCuestionarioAccess().getCategoriasAssignment_5(), "rule__Cuestionario__CategoriasAssignment_5");
			builder.put(grammarAccess.getCuestionarioAccess().getCategoriasAssignment_6_1(), "rule__Cuestionario__CategoriasAssignment_6_1");
			builder.put(grammarAccess.getCuestionarioAccess().getPreguntaInicialAssignment_8(), "rule__Cuestionario__PreguntaInicialAssignment_8");
			builder.put(grammarAccess.getCuestionarioAccess().getPreguntasFinalesAssignment_10(), "rule__Cuestionario__PreguntasFinalesAssignment_10");
			builder.put(grammarAccess.getCuestionarioAccess().getPreguntasFinalesAssignment_11_1(), "rule__Cuestionario__PreguntasFinalesAssignment_11_1");
			builder.put(grammarAccess.getCategoriaAccess().getNameAssignment_1(), "rule__Categoria__NameAssignment_1");
			builder.put(grammarAccess.getCategoriaAccess().getDificultadAssignment_4(), "rule__Categoria__DificultadAssignment_4");
			builder.put(grammarAccess.getCategoriaAccess().getSubcategoriasAssignment_5_1(), "rule__Categoria__SubcategoriasAssignment_5_1");
			builder.put(grammarAccess.getCategoriaAccess().getSubcategoriasAssignment_5_2_1(), "rule__Categoria__SubcategoriasAssignment_5_2_1");
			builder.put(grammarAccess.getPreguntaUnicaAccess().getNameAssignment_1(), "rule__PreguntaUnica__NameAssignment_1");
			builder.put(grammarAccess.getPreguntaUnicaAccess().getEnunciadoAssignment_4(), "rule__PreguntaUnica__EnunciadoAssignment_4");
			builder.put(grammarAccess.getPreguntaUnicaAccess().getRespuestasAssignment_7(), "rule__PreguntaUnica__RespuestasAssignment_7");
			builder.put(grammarAccess.getPreguntaUnicaAccess().getRespuestasAssignment_8_1(), "rule__PreguntaUnica__RespuestasAssignment_8_1");
			builder.put(grammarAccess.getPreguntaUnicaAccess().getPuntuacionAssignment_11(), "rule__PreguntaUnica__PuntuacionAssignment_11");
			builder.put(grammarAccess.getPreguntaUnicaAccess().getPenalizacionAssignment_13(), "rule__PreguntaUnica__PenalizacionAssignment_13");
			builder.put(grammarAccess.getPreguntaUnicaAccess().getCategoriaAssignment_15(), "rule__PreguntaUnica__CategoriaAssignment_15");
			builder.put(grammarAccess.getPreguntaUnicaAccess().getCorrectaAssignment_17(), "rule__PreguntaUnica__CorrectaAssignment_17");
			builder.put(grammarAccess.getPreguntaUnicaAccess().getIsInicialAssignment_18_0(), "rule__PreguntaUnica__IsInicialAssignment_18_0");
			builder.put(grammarAccess.getPreguntaUnicaAccess().getSiguientePreguntaAciertoAssignment_18_2_1(), "rule__PreguntaUnica__SiguientePreguntaAciertoAssignment_18_2_1");
			builder.put(grammarAccess.getPreguntaUnicaAccess().getSiguientePreguntaErrorAssignment_18_4_1(), "rule__PreguntaUnica__SiguientePreguntaErrorAssignment_18_4_1");
			builder.put(grammarAccess.getPreguntaMultipleAccess().getNameAssignment_1(), "rule__PreguntaMultiple__NameAssignment_1");
			builder.put(grammarAccess.getPreguntaMultipleAccess().getEnunciadoAssignment_4(), "rule__PreguntaMultiple__EnunciadoAssignment_4");
			builder.put(grammarAccess.getPreguntaMultipleAccess().getRespuestasAssignment_7(), "rule__PreguntaMultiple__RespuestasAssignment_7");
			builder.put(grammarAccess.getPreguntaMultipleAccess().getRespuestasAssignment_8_1(), "rule__PreguntaMultiple__RespuestasAssignment_8_1");
			builder.put(grammarAccess.getPreguntaMultipleAccess().getPuntuacionAssignment_11(), "rule__PreguntaMultiple__PuntuacionAssignment_11");
			builder.put(grammarAccess.getPreguntaMultipleAccess().getPenalizacionAssignment_13(), "rule__PreguntaMultiple__PenalizacionAssignment_13");
			builder.put(grammarAccess.getPreguntaMultipleAccess().getCategoriaAssignment_15(), "rule__PreguntaMultiple__CategoriaAssignment_15");
			builder.put(grammarAccess.getPreguntaMultipleAccess().getCorrectasAssignment_16_1(), "rule__PreguntaMultiple__CorrectasAssignment_16_1");
			builder.put(grammarAccess.getPreguntaMultipleAccess().getCorrectasAssignment_16_2_1(), "rule__PreguntaMultiple__CorrectasAssignment_16_2_1");
			builder.put(grammarAccess.getPreguntaMultipleAccess().getIsInicialAssignment_17_0(), "rule__PreguntaMultiple__IsInicialAssignment_17_0");
			builder.put(grammarAccess.getPreguntaMultipleAccess().getSiguientePreguntaAciertoAssignment_17_2_1(), "rule__PreguntaMultiple__SiguientePreguntaAciertoAssignment_17_2_1");
			builder.put(grammarAccess.getPreguntaMultipleAccess().getSiguientePreguntaErrorAssignment_17_4_1(), "rule__PreguntaMultiple__SiguientePreguntaErrorAssignment_17_4_1");
			builder.put(grammarAccess.getRespuestaAccess().getNameAssignment_0(), "rule__Respuesta__NameAssignment_0");
			builder.put(grammarAccess.getRespuestaAccess().getOpcionAssignment_2(), "rule__Respuesta__OpcionAssignment_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private CuestionarioGrammarAccess grammarAccess;

	@Override
	protected InternalCuestionarioParser createParser() {
		InternalCuestionarioParser result = new InternalCuestionarioParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public CuestionarioGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CuestionarioGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
