/*
 * generated by Xtext 2.26.0
 */
package cuestionario.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCuestionarioScopeProvider extends DelegatingScopeProvider {
}
