/*
 * generated by Xtext 2.26.0
 */
package cuestionario.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CuestionarioAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("cuestionario/parser/antlr/internal/InternalCuestionario.tokens");
	}
}
