/*
 * generated by Xtext 2.26.0
 */
package cuestionario;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CuestionarioStandaloneSetup extends CuestionarioStandaloneSetupGenerated {

	public static void doSetup() {
		new CuestionarioStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
