/*
 * generated by Xtext 2.26.0
 */
package cuestionario.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class CuestionarioGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class CuestionarioElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuestionario.Cuestionario.Cuestionario");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCuestionarioKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cPreguntasKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cPreguntasAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cPreguntasPreguntaParserRuleCall_2_0 = (RuleCall)cPreguntasAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCommaKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cPreguntasAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cPreguntasPreguntaParserRuleCall_3_1_0 = (RuleCall)cPreguntasAssignment_3_1.eContents().get(0);
		private final Keyword cCategoriasKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cCategoriasAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cCategoriasCategoriaParserRuleCall_5_0 = (RuleCall)cCategoriasAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cCategoriasAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cCategoriasCategoriaParserRuleCall_6_1_0 = (RuleCall)cCategoriasAssignment_6_1.eContents().get(0);
		private final Keyword cInicialKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cPreguntaInicialAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final CrossReference cPreguntaInicialPreguntaCrossReference_8_0 = (CrossReference)cPreguntaInicialAssignment_8.eContents().get(0);
		private final RuleCall cPreguntaInicialPreguntaEStringParserRuleCall_8_0_1 = (RuleCall)cPreguntaInicialPreguntaCrossReference_8_0.eContents().get(1);
		private final Keyword cFinalesKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cPreguntasFinalesAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final CrossReference cPreguntasFinalesPreguntaCrossReference_10_0 = (CrossReference)cPreguntasFinalesAssignment_10.eContents().get(0);
		private final RuleCall cPreguntasFinalesPreguntaEStringParserRuleCall_10_0_1 = (RuleCall)cPreguntasFinalesPreguntaCrossReference_10_0.eContents().get(1);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cCommaKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cPreguntasFinalesAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final CrossReference cPreguntasFinalesPreguntaCrossReference_11_1_0 = (CrossReference)cPreguntasFinalesAssignment_11_1.eContents().get(0);
		private final RuleCall cPreguntasFinalesPreguntaEStringParserRuleCall_11_1_0_1 = (RuleCall)cPreguntasFinalesPreguntaCrossReference_11_1_0.eContents().get(1);
		
		//Cuestionario returns Cuestionario:
		//    'Cuestionario'
		//        'Preguntas:' preguntas+=Pregunta ( "," preguntas+=Pregunta)*
		//        'Categorias:' categorias+=Categoria ( "," categorias+=Categoria)*
		//        'Inicial:' preguntaInicial=[Pregunta|EString]
		//        'Finales:' preguntasFinales+=[Pregunta|EString] ( "," preguntasFinales+=[Pregunta|EString])* ;
		@Override public ParserRule getRule() { return rule; }
		
		//'Cuestionario'
		//    'Preguntas:' preguntas+=Pregunta ( "," preguntas+=Pregunta)*
		//    'Categorias:' categorias+=Categoria ( "," categorias+=Categoria)*
		//    'Inicial:' preguntaInicial=[Pregunta|EString]
		//    'Finales:' preguntasFinales+=[Pregunta|EString] ( "," preguntasFinales+=[Pregunta|EString])*
		public Group getGroup() { return cGroup; }
		
		//'Cuestionario'
		public Keyword getCuestionarioKeyword_0() { return cCuestionarioKeyword_0; }
		
		//'Preguntas:'
		public Keyword getPreguntasKeyword_1() { return cPreguntasKeyword_1; }
		
		//preguntas+=Pregunta
		public Assignment getPreguntasAssignment_2() { return cPreguntasAssignment_2; }
		
		//Pregunta
		public RuleCall getPreguntasPreguntaParserRuleCall_2_0() { return cPreguntasPreguntaParserRuleCall_2_0; }
		
		//( "," preguntas+=Pregunta)*
		public Group getGroup_3() { return cGroup_3; }
		
		//","
		public Keyword getCommaKeyword_3_0() { return cCommaKeyword_3_0; }
		
		//preguntas+=Pregunta
		public Assignment getPreguntasAssignment_3_1() { return cPreguntasAssignment_3_1; }
		
		//Pregunta
		public RuleCall getPreguntasPreguntaParserRuleCall_3_1_0() { return cPreguntasPreguntaParserRuleCall_3_1_0; }
		
		//'Categorias:'
		public Keyword getCategoriasKeyword_4() { return cCategoriasKeyword_4; }
		
		//categorias+=Categoria
		public Assignment getCategoriasAssignment_5() { return cCategoriasAssignment_5; }
		
		//Categoria
		public RuleCall getCategoriasCategoriaParserRuleCall_5_0() { return cCategoriasCategoriaParserRuleCall_5_0; }
		
		//( "," categorias+=Categoria)*
		public Group getGroup_6() { return cGroup_6; }
		
		//","
		public Keyword getCommaKeyword_6_0() { return cCommaKeyword_6_0; }
		
		//categorias+=Categoria
		public Assignment getCategoriasAssignment_6_1() { return cCategoriasAssignment_6_1; }
		
		//Categoria
		public RuleCall getCategoriasCategoriaParserRuleCall_6_1_0() { return cCategoriasCategoriaParserRuleCall_6_1_0; }
		
		//'Inicial:'
		public Keyword getInicialKeyword_7() { return cInicialKeyword_7; }
		
		//preguntaInicial=[Pregunta|EString]
		public Assignment getPreguntaInicialAssignment_8() { return cPreguntaInicialAssignment_8; }
		
		//[Pregunta|EString]
		public CrossReference getPreguntaInicialPreguntaCrossReference_8_0() { return cPreguntaInicialPreguntaCrossReference_8_0; }
		
		//EString
		public RuleCall getPreguntaInicialPreguntaEStringParserRuleCall_8_0_1() { return cPreguntaInicialPreguntaEStringParserRuleCall_8_0_1; }
		
		//'Finales:'
		public Keyword getFinalesKeyword_9() { return cFinalesKeyword_9; }
		
		//preguntasFinales+=[Pregunta|EString]
		public Assignment getPreguntasFinalesAssignment_10() { return cPreguntasFinalesAssignment_10; }
		
		//[Pregunta|EString]
		public CrossReference getPreguntasFinalesPreguntaCrossReference_10_0() { return cPreguntasFinalesPreguntaCrossReference_10_0; }
		
		//EString
		public RuleCall getPreguntasFinalesPreguntaEStringParserRuleCall_10_0_1() { return cPreguntasFinalesPreguntaEStringParserRuleCall_10_0_1; }
		
		//( "," preguntasFinales+=[Pregunta|EString])*
		public Group getGroup_11() { return cGroup_11; }
		
		//","
		public Keyword getCommaKeyword_11_0() { return cCommaKeyword_11_0; }
		
		//preguntasFinales+=[Pregunta|EString]
		public Assignment getPreguntasFinalesAssignment_11_1() { return cPreguntasFinalesAssignment_11_1; }
		
		//[Pregunta|EString]
		public CrossReference getPreguntasFinalesPreguntaCrossReference_11_1_0() { return cPreguntasFinalesPreguntaCrossReference_11_1_0; }
		
		//EString
		public RuleCall getPreguntasFinalesPreguntaEStringParserRuleCall_11_1_0_1() { return cPreguntasFinalesPreguntaEStringParserRuleCall_11_1_0_1; }
	}
	public class PreguntaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuestionario.Cuestionario.Pregunta");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cPreguntaUnicaParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cPreguntaMultipleParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Pregunta returns Pregunta:
		//    PreguntaUnica | PreguntaMultiple;
		@Override public ParserRule getRule() { return rule; }
		
		//PreguntaUnica | PreguntaMultiple
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//PreguntaUnica
		public RuleCall getPreguntaUnicaParserRuleCall_0() { return cPreguntaUnicaParserRuleCall_0; }
		
		//PreguntaMultiple
		public RuleCall getPreguntaMultipleParserRuleCall_1() { return cPreguntaMultipleParserRuleCall_1; }
	}
	public class CategoriaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuestionario.Cuestionario.Categoria");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCategoriaKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cDificultadKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDificultadAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDificultadEDoubleParserRuleCall_4_0 = (RuleCall)cDificultadAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cSubCategoriasKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cSubcategoriasAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cSubcategoriasCategoriaParserRuleCall_5_1_0 = (RuleCall)cSubcategoriasAssignment_5_1.eContents().get(0);
		private final Group cGroup_5_2 = (Group)cGroup_5.eContents().get(2);
		private final Keyword cCommaKeyword_5_2_0 = (Keyword)cGroup_5_2.eContents().get(0);
		private final Assignment cSubcategoriasAssignment_5_2_1 = (Assignment)cGroup_5_2.eContents().get(1);
		private final RuleCall cSubcategoriasCategoriaParserRuleCall_5_2_1_0 = (RuleCall)cSubcategoriasAssignment_5_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Categoria returns Categoria:
		//    'categoria'
		//    name=EString
		//    '{'
		//        'dificultad' dificultad=EDouble
		//        ('SubCategorias:' subcategorias+=Categoria ( "," subcategorias+=Categoria)*)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'categoria'
		//name=EString
		//'{'
		//    'dificultad' dificultad=EDouble
		//    ('SubCategorias:' subcategorias+=Categoria ( "," subcategorias+=Categoria)*)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'categoria'
		public Keyword getCategoriaKeyword_0() { return cCategoriaKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'dificultad'
		public Keyword getDificultadKeyword_3() { return cDificultadKeyword_3; }
		
		//dificultad=EDouble
		public Assignment getDificultadAssignment_4() { return cDificultadAssignment_4; }
		
		//EDouble
		public RuleCall getDificultadEDoubleParserRuleCall_4_0() { return cDificultadEDoubleParserRuleCall_4_0; }
		
		//('SubCategorias:' subcategorias+=Categoria ( "," subcategorias+=Categoria)*)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'SubCategorias:'
		public Keyword getSubCategoriasKeyword_5_0() { return cSubCategoriasKeyword_5_0; }
		
		//subcategorias+=Categoria
		public Assignment getSubcategoriasAssignment_5_1() { return cSubcategoriasAssignment_5_1; }
		
		//Categoria
		public RuleCall getSubcategoriasCategoriaParserRuleCall_5_1_0() { return cSubcategoriasCategoriaParserRuleCall_5_1_0; }
		
		//( "," subcategorias+=Categoria)*
		public Group getGroup_5_2() { return cGroup_5_2; }
		
		//","
		public Keyword getCommaKeyword_5_2_0() { return cCommaKeyword_5_2_0; }
		
		//subcategorias+=Categoria
		public Assignment getSubcategoriasAssignment_5_2_1() { return cSubcategoriasAssignment_5_2_1; }
		
		//Categoria
		public RuleCall getSubcategoriasCategoriaParserRuleCall_5_2_1_0() { return cSubcategoriasCategoriaParserRuleCall_5_2_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuestionario.Cuestionario.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class EDoubleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuestionario.Cuestionario.EDouble");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EDouble returns ecore::EDouble:
		//    '-'? INT? '.' INT (('E'|'e') '-'? INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT? '.' INT (('E'|'e') '-'? INT)?
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
		
		//(('E'|'e') '-'? INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//('E'|'e')
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }
		
		//'E'
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }
		
		//'e'
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuestionario.Cuestionario.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//    'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class PreguntaUnicaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuestionario.Cuestionario.PreguntaUnica");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPregUnicaKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cEnunciadoKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cEnunciadoAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cEnunciadoEStringParserRuleCall_4_0 = (RuleCall)cEnunciadoAssignment_4.eContents().get(0);
		private final Keyword cRespuestasKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cRespuestasAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cRespuestasRespuestaParserRuleCall_7_0 = (RuleCall)cRespuestasAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommaKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cRespuestasAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cRespuestasRespuestaParserRuleCall_8_1_0 = (RuleCall)cRespuestasAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cPuntuacionKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cPuntuacionAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cPuntuacionEDoubleParserRuleCall_11_0 = (RuleCall)cPuntuacionAssignment_11.eContents().get(0);
		private final Keyword cPenalizacionKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cPenalizacionAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cPenalizacionEDoubleParserRuleCall_13_0 = (RuleCall)cPenalizacionAssignment_13.eContents().get(0);
		private final Keyword cCategoriaKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Assignment cCategoriaAssignment_15 = (Assignment)cGroup.eContents().get(15);
		private final CrossReference cCategoriaCategoriaCrossReference_15_0 = (CrossReference)cCategoriaAssignment_15.eContents().get(0);
		private final RuleCall cCategoriaCategoriaEStringParserRuleCall_15_0_1 = (RuleCall)cCategoriaCategoriaCrossReference_15_0.eContents().get(1);
		private final Keyword cCorrectaKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Assignment cCorrectaAssignment_17 = (Assignment)cGroup.eContents().get(17);
		private final CrossReference cCorrectaRespuestaCrossReference_17_0 = (CrossReference)cCorrectaAssignment_17.eContents().get(0);
		private final RuleCall cCorrectaRespuestaEStringParserRuleCall_17_0_1 = (RuleCall)cCorrectaRespuestaCrossReference_17_0.eContents().get(1);
		private final Group cGroup_18 = (Group)cGroup.eContents().get(18);
		private final Assignment cIsInicialAssignment_18_0 = (Assignment)cGroup_18.eContents().get(0);
		private final Keyword cIsInicialIsInicialKeyword_18_0_0 = (Keyword)cIsInicialAssignment_18_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_18_1 = (Keyword)cGroup_18.eContents().get(1);
		private final Group cGroup_18_2 = (Group)cGroup_18.eContents().get(2);
		private final Keyword cSiguientePreguntaAciertoKeyword_18_2_0 = (Keyword)cGroup_18_2.eContents().get(0);
		private final Assignment cSiguientePreguntaAciertoAssignment_18_2_1 = (Assignment)cGroup_18_2.eContents().get(1);
		private final CrossReference cSiguientePreguntaAciertoPreguntaCrossReference_18_2_1_0 = (CrossReference)cSiguientePreguntaAciertoAssignment_18_2_1.eContents().get(0);
		private final RuleCall cSiguientePreguntaAciertoPreguntaEStringParserRuleCall_18_2_1_0_1 = (RuleCall)cSiguientePreguntaAciertoPreguntaCrossReference_18_2_1_0.eContents().get(1);
		private final Keyword cCommaKeyword_18_3 = (Keyword)cGroup_18.eContents().get(3);
		private final Group cGroup_18_4 = (Group)cGroup_18.eContents().get(4);
		private final Keyword cSiguientePreguntaErrorKeyword_18_4_0 = (Keyword)cGroup_18_4.eContents().get(0);
		private final Assignment cSiguientePreguntaErrorAssignment_18_4_1 = (Assignment)cGroup_18_4.eContents().get(1);
		private final CrossReference cSiguientePreguntaErrorPreguntaCrossReference_18_4_1_0 = (CrossReference)cSiguientePreguntaErrorAssignment_18_4_1.eContents().get(0);
		private final RuleCall cSiguientePreguntaErrorPreguntaEStringParserRuleCall_18_4_1_0_1 = (RuleCall)cSiguientePreguntaErrorPreguntaCrossReference_18_4_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_18_5 = (Keyword)cGroup_18.eContents().get(5);
		private final Keyword cRightCurlyBracketKeyword_19 = (Keyword)cGroup.eContents().get(19);
		
		//PreguntaUnica returns PreguntaUnica:
		//    'pregUnica'
		//    name=EString
		//    '{'
		//        'Enunciado:' enunciado=EString
		//        'Respuestas' '{' respuestas+=Respuesta ( "," respuestas+=Respuesta)* '}'
		//        'Puntuacion:' puntuacion=EDouble
		//        'Penalizacion:' penalizacion=EDouble
		//        'Categoria:' categoria=[Categoria|EString]
		//        'Correcta:' correcta=[Respuesta|EString]
		//        ((isInicial?='isInicial')
		//        '('
		//        ('siguientePreguntaAcierto:' siguientePreguntaAcierto=[Pregunta|EString])
		//        (',')
		//        ('siguientePreguntaError:' siguientePreguntaError=[Pregunta|EString])
		//        ')')?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'pregUnica'
		//name=EString
		//'{'
		//    'Enunciado:' enunciado=EString
		//    'Respuestas' '{' respuestas+=Respuesta ( "," respuestas+=Respuesta)* '}'
		//    'Puntuacion:' puntuacion=EDouble
		//    'Penalizacion:' penalizacion=EDouble
		//    'Categoria:' categoria=[Categoria|EString]
		//    'Correcta:' correcta=[Respuesta|EString]
		//    ((isInicial?='isInicial')
		//    '('
		//    ('siguientePreguntaAcierto:' siguientePreguntaAcierto=[Pregunta|EString])
		//    (',')
		//    ('siguientePreguntaError:' siguientePreguntaError=[Pregunta|EString])
		//    ')')?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'pregUnica'
		public Keyword getPregUnicaKeyword_0() { return cPregUnicaKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'Enunciado:'
		public Keyword getEnunciadoKeyword_3() { return cEnunciadoKeyword_3; }
		
		//enunciado=EString
		public Assignment getEnunciadoAssignment_4() { return cEnunciadoAssignment_4; }
		
		//EString
		public RuleCall getEnunciadoEStringParserRuleCall_4_0() { return cEnunciadoEStringParserRuleCall_4_0; }
		
		//'Respuestas'
		public Keyword getRespuestasKeyword_5() { return cRespuestasKeyword_5; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }
		
		//respuestas+=Respuesta
		public Assignment getRespuestasAssignment_7() { return cRespuestasAssignment_7; }
		
		//Respuesta
		public RuleCall getRespuestasRespuestaParserRuleCall_7_0() { return cRespuestasRespuestaParserRuleCall_7_0; }
		
		//( "," respuestas+=Respuesta)*
		public Group getGroup_8() { return cGroup_8; }
		
		//","
		public Keyword getCommaKeyword_8_0() { return cCommaKeyword_8_0; }
		
		//respuestas+=Respuesta
		public Assignment getRespuestasAssignment_8_1() { return cRespuestasAssignment_8_1; }
		
		//Respuesta
		public RuleCall getRespuestasRespuestaParserRuleCall_8_1_0() { return cRespuestasRespuestaParserRuleCall_8_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
		
		//'Puntuacion:'
		public Keyword getPuntuacionKeyword_10() { return cPuntuacionKeyword_10; }
		
		//puntuacion=EDouble
		public Assignment getPuntuacionAssignment_11() { return cPuntuacionAssignment_11; }
		
		//EDouble
		public RuleCall getPuntuacionEDoubleParserRuleCall_11_0() { return cPuntuacionEDoubleParserRuleCall_11_0; }
		
		//'Penalizacion:'
		public Keyword getPenalizacionKeyword_12() { return cPenalizacionKeyword_12; }
		
		//penalizacion=EDouble
		public Assignment getPenalizacionAssignment_13() { return cPenalizacionAssignment_13; }
		
		//EDouble
		public RuleCall getPenalizacionEDoubleParserRuleCall_13_0() { return cPenalizacionEDoubleParserRuleCall_13_0; }
		
		//'Categoria:'
		public Keyword getCategoriaKeyword_14() { return cCategoriaKeyword_14; }
		
		//categoria=[Categoria|EString]
		public Assignment getCategoriaAssignment_15() { return cCategoriaAssignment_15; }
		
		//[Categoria|EString]
		public CrossReference getCategoriaCategoriaCrossReference_15_0() { return cCategoriaCategoriaCrossReference_15_0; }
		
		//EString
		public RuleCall getCategoriaCategoriaEStringParserRuleCall_15_0_1() { return cCategoriaCategoriaEStringParserRuleCall_15_0_1; }
		
		//'Correcta:'
		public Keyword getCorrectaKeyword_16() { return cCorrectaKeyword_16; }
		
		//correcta=[Respuesta|EString]
		public Assignment getCorrectaAssignment_17() { return cCorrectaAssignment_17; }
		
		//[Respuesta|EString]
		public CrossReference getCorrectaRespuestaCrossReference_17_0() { return cCorrectaRespuestaCrossReference_17_0; }
		
		//EString
		public RuleCall getCorrectaRespuestaEStringParserRuleCall_17_0_1() { return cCorrectaRespuestaEStringParserRuleCall_17_0_1; }
		
		//((isInicial?='isInicial')
		//'('
		//('siguientePreguntaAcierto:' siguientePreguntaAcierto=[Pregunta|EString])
		//(',')
		//('siguientePreguntaError:' siguientePreguntaError=[Pregunta|EString])
		//')')?
		public Group getGroup_18() { return cGroup_18; }
		
		//(isInicial?='isInicial')
		public Assignment getIsInicialAssignment_18_0() { return cIsInicialAssignment_18_0; }
		
		//'isInicial'
		public Keyword getIsInicialIsInicialKeyword_18_0_0() { return cIsInicialIsInicialKeyword_18_0_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_18_1() { return cLeftParenthesisKeyword_18_1; }
		
		//('siguientePreguntaAcierto:' siguientePreguntaAcierto=[Pregunta|EString])
		public Group getGroup_18_2() { return cGroup_18_2; }
		
		//'siguientePreguntaAcierto:'
		public Keyword getSiguientePreguntaAciertoKeyword_18_2_0() { return cSiguientePreguntaAciertoKeyword_18_2_0; }
		
		//siguientePreguntaAcierto=[Pregunta|EString]
		public Assignment getSiguientePreguntaAciertoAssignment_18_2_1() { return cSiguientePreguntaAciertoAssignment_18_2_1; }
		
		//[Pregunta|EString]
		public CrossReference getSiguientePreguntaAciertoPreguntaCrossReference_18_2_1_0() { return cSiguientePreguntaAciertoPreguntaCrossReference_18_2_1_0; }
		
		//EString
		public RuleCall getSiguientePreguntaAciertoPreguntaEStringParserRuleCall_18_2_1_0_1() { return cSiguientePreguntaAciertoPreguntaEStringParserRuleCall_18_2_1_0_1; }
		
		//(',')
		public Keyword getCommaKeyword_18_3() { return cCommaKeyword_18_3; }
		
		//('siguientePreguntaError:' siguientePreguntaError=[Pregunta|EString])
		public Group getGroup_18_4() { return cGroup_18_4; }
		
		//'siguientePreguntaError:'
		public Keyword getSiguientePreguntaErrorKeyword_18_4_0() { return cSiguientePreguntaErrorKeyword_18_4_0; }
		
		//siguientePreguntaError=[Pregunta|EString]
		public Assignment getSiguientePreguntaErrorAssignment_18_4_1() { return cSiguientePreguntaErrorAssignment_18_4_1; }
		
		//[Pregunta|EString]
		public CrossReference getSiguientePreguntaErrorPreguntaCrossReference_18_4_1_0() { return cSiguientePreguntaErrorPreguntaCrossReference_18_4_1_0; }
		
		//EString
		public RuleCall getSiguientePreguntaErrorPreguntaEStringParserRuleCall_18_4_1_0_1() { return cSiguientePreguntaErrorPreguntaEStringParserRuleCall_18_4_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_18_5() { return cRightParenthesisKeyword_18_5; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_19() { return cRightCurlyBracketKeyword_19; }
	}
	public class PreguntaMultipleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuestionario.Cuestionario.PreguntaMultiple");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPregMultipleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cEnunciadoKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cEnunciadoAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cEnunciadoEStringParserRuleCall_4_0 = (RuleCall)cEnunciadoAssignment_4.eContents().get(0);
		private final Keyword cRespuestasKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cRespuestasAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cRespuestasRespuestaParserRuleCall_7_0 = (RuleCall)cRespuestasAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommaKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cRespuestasAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cRespuestasRespuestaParserRuleCall_8_1_0 = (RuleCall)cRespuestasAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cPuntuacionKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cPuntuacionAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cPuntuacionEDoubleParserRuleCall_11_0 = (RuleCall)cPuntuacionAssignment_11.eContents().get(0);
		private final Keyword cPenalizacionKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cPenalizacionAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cPenalizacionEDoubleParserRuleCall_13_0 = (RuleCall)cPenalizacionAssignment_13.eContents().get(0);
		private final Keyword cCategoriaKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Assignment cCategoriaAssignment_15 = (Assignment)cGroup.eContents().get(15);
		private final CrossReference cCategoriaCategoriaCrossReference_15_0 = (CrossReference)cCategoriaAssignment_15.eContents().get(0);
		private final RuleCall cCategoriaCategoriaEStringParserRuleCall_15_0_1 = (RuleCall)cCategoriaCategoriaCrossReference_15_0.eContents().get(1);
		private final Group cGroup_16 = (Group)cGroup.eContents().get(16);
		private final Keyword cCorrectasKeyword_16_0 = (Keyword)cGroup_16.eContents().get(0);
		private final Assignment cCorrectasAssignment_16_1 = (Assignment)cGroup_16.eContents().get(1);
		private final CrossReference cCorrectasRespuestaCrossReference_16_1_0 = (CrossReference)cCorrectasAssignment_16_1.eContents().get(0);
		private final RuleCall cCorrectasRespuestaEStringParserRuleCall_16_1_0_1 = (RuleCall)cCorrectasRespuestaCrossReference_16_1_0.eContents().get(1);
		private final Group cGroup_16_2 = (Group)cGroup_16.eContents().get(2);
		private final Keyword cCommaKeyword_16_2_0 = (Keyword)cGroup_16_2.eContents().get(0);
		private final Assignment cCorrectasAssignment_16_2_1 = (Assignment)cGroup_16_2.eContents().get(1);
		private final CrossReference cCorrectasRespuestaCrossReference_16_2_1_0 = (CrossReference)cCorrectasAssignment_16_2_1.eContents().get(0);
		private final RuleCall cCorrectasRespuestaEStringParserRuleCall_16_2_1_0_1 = (RuleCall)cCorrectasRespuestaCrossReference_16_2_1_0.eContents().get(1);
		private final Group cGroup_17 = (Group)cGroup.eContents().get(17);
		private final Assignment cIsInicialAssignment_17_0 = (Assignment)cGroup_17.eContents().get(0);
		private final Keyword cIsInicialIsInicialKeyword_17_0_0 = (Keyword)cIsInicialAssignment_17_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_17_1 = (Keyword)cGroup_17.eContents().get(1);
		private final Group cGroup_17_2 = (Group)cGroup_17.eContents().get(2);
		private final Keyword cSiguientePreguntaAciertoKeyword_17_2_0 = (Keyword)cGroup_17_2.eContents().get(0);
		private final Assignment cSiguientePreguntaAciertoAssignment_17_2_1 = (Assignment)cGroup_17_2.eContents().get(1);
		private final CrossReference cSiguientePreguntaAciertoPreguntaCrossReference_17_2_1_0 = (CrossReference)cSiguientePreguntaAciertoAssignment_17_2_1.eContents().get(0);
		private final RuleCall cSiguientePreguntaAciertoPreguntaEStringParserRuleCall_17_2_1_0_1 = (RuleCall)cSiguientePreguntaAciertoPreguntaCrossReference_17_2_1_0.eContents().get(1);
		private final Keyword cCommaKeyword_17_3 = (Keyword)cGroup_17.eContents().get(3);
		private final Group cGroup_17_4 = (Group)cGroup_17.eContents().get(4);
		private final Keyword cSiguientePreguntaErrorKeyword_17_4_0 = (Keyword)cGroup_17_4.eContents().get(0);
		private final Assignment cSiguientePreguntaErrorAssignment_17_4_1 = (Assignment)cGroup_17_4.eContents().get(1);
		private final CrossReference cSiguientePreguntaErrorPreguntaCrossReference_17_4_1_0 = (CrossReference)cSiguientePreguntaErrorAssignment_17_4_1.eContents().get(0);
		private final RuleCall cSiguientePreguntaErrorPreguntaEStringParserRuleCall_17_4_1_0_1 = (RuleCall)cSiguientePreguntaErrorPreguntaCrossReference_17_4_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_17_5 = (Keyword)cGroup_17.eContents().get(5);
		private final Keyword cRightCurlyBracketKeyword_18 = (Keyword)cGroup.eContents().get(18);
		
		//PreguntaMultiple returns PreguntaMultiple:
		//    'pregMultiple'
		//    name=EString
		//    '{'
		//        'Enunciado:' enunciado=EString
		//        'Respuestas' '{' respuestas+=Respuesta ( "," respuestas+=Respuesta)* '}'
		//        'Puntuacion:' puntuacion=EDouble
		//        'Penalizacion:' penalizacion=EDouble
		//        'Categoria:' categoria=[Categoria|EString]
		//        ('Correctas:' correctas+=[Respuesta|EString] ( "," correctas+=[Respuesta|EString])*)?
		//        ((isInicial?='isInicial')
		//        '('
		//        ('siguientePreguntaAcierto:' siguientePreguntaAcierto=[Pregunta|EString])
		//        (',')
		//        ('siguientePreguntaError:' siguientePreguntaError=[Pregunta|EString])
		//        ')')?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'pregMultiple'
		//name=EString
		//'{'
		//    'Enunciado:' enunciado=EString
		//    'Respuestas' '{' respuestas+=Respuesta ( "," respuestas+=Respuesta)* '}'
		//    'Puntuacion:' puntuacion=EDouble
		//    'Penalizacion:' penalizacion=EDouble
		//    'Categoria:' categoria=[Categoria|EString]
		//    ('Correctas:' correctas+=[Respuesta|EString] ( "," correctas+=[Respuesta|EString])*)?
		//    ((isInicial?='isInicial')
		//    '('
		//    ('siguientePreguntaAcierto:' siguientePreguntaAcierto=[Pregunta|EString])
		//    (',')
		//    ('siguientePreguntaError:' siguientePreguntaError=[Pregunta|EString])
		//    ')')?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'pregMultiple'
		public Keyword getPregMultipleKeyword_0() { return cPregMultipleKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'Enunciado:'
		public Keyword getEnunciadoKeyword_3() { return cEnunciadoKeyword_3; }
		
		//enunciado=EString
		public Assignment getEnunciadoAssignment_4() { return cEnunciadoAssignment_4; }
		
		//EString
		public RuleCall getEnunciadoEStringParserRuleCall_4_0() { return cEnunciadoEStringParserRuleCall_4_0; }
		
		//'Respuestas'
		public Keyword getRespuestasKeyword_5() { return cRespuestasKeyword_5; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }
		
		//respuestas+=Respuesta
		public Assignment getRespuestasAssignment_7() { return cRespuestasAssignment_7; }
		
		//Respuesta
		public RuleCall getRespuestasRespuestaParserRuleCall_7_0() { return cRespuestasRespuestaParserRuleCall_7_0; }
		
		//( "," respuestas+=Respuesta)*
		public Group getGroup_8() { return cGroup_8; }
		
		//","
		public Keyword getCommaKeyword_8_0() { return cCommaKeyword_8_0; }
		
		//respuestas+=Respuesta
		public Assignment getRespuestasAssignment_8_1() { return cRespuestasAssignment_8_1; }
		
		//Respuesta
		public RuleCall getRespuestasRespuestaParserRuleCall_8_1_0() { return cRespuestasRespuestaParserRuleCall_8_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
		
		//'Puntuacion:'
		public Keyword getPuntuacionKeyword_10() { return cPuntuacionKeyword_10; }
		
		//puntuacion=EDouble
		public Assignment getPuntuacionAssignment_11() { return cPuntuacionAssignment_11; }
		
		//EDouble
		public RuleCall getPuntuacionEDoubleParserRuleCall_11_0() { return cPuntuacionEDoubleParserRuleCall_11_0; }
		
		//'Penalizacion:'
		public Keyword getPenalizacionKeyword_12() { return cPenalizacionKeyword_12; }
		
		//penalizacion=EDouble
		public Assignment getPenalizacionAssignment_13() { return cPenalizacionAssignment_13; }
		
		//EDouble
		public RuleCall getPenalizacionEDoubleParserRuleCall_13_0() { return cPenalizacionEDoubleParserRuleCall_13_0; }
		
		//'Categoria:'
		public Keyword getCategoriaKeyword_14() { return cCategoriaKeyword_14; }
		
		//categoria=[Categoria|EString]
		public Assignment getCategoriaAssignment_15() { return cCategoriaAssignment_15; }
		
		//[Categoria|EString]
		public CrossReference getCategoriaCategoriaCrossReference_15_0() { return cCategoriaCategoriaCrossReference_15_0; }
		
		//EString
		public RuleCall getCategoriaCategoriaEStringParserRuleCall_15_0_1() { return cCategoriaCategoriaEStringParserRuleCall_15_0_1; }
		
		//('Correctas:' correctas+=[Respuesta|EString] ( "," correctas+=[Respuesta|EString])*)?
		public Group getGroup_16() { return cGroup_16; }
		
		//'Correctas:'
		public Keyword getCorrectasKeyword_16_0() { return cCorrectasKeyword_16_0; }
		
		//correctas+=[Respuesta|EString]
		public Assignment getCorrectasAssignment_16_1() { return cCorrectasAssignment_16_1; }
		
		//[Respuesta|EString]
		public CrossReference getCorrectasRespuestaCrossReference_16_1_0() { return cCorrectasRespuestaCrossReference_16_1_0; }
		
		//EString
		public RuleCall getCorrectasRespuestaEStringParserRuleCall_16_1_0_1() { return cCorrectasRespuestaEStringParserRuleCall_16_1_0_1; }
		
		//( "," correctas+=[Respuesta|EString])*
		public Group getGroup_16_2() { return cGroup_16_2; }
		
		//","
		public Keyword getCommaKeyword_16_2_0() { return cCommaKeyword_16_2_0; }
		
		//correctas+=[Respuesta|EString]
		public Assignment getCorrectasAssignment_16_2_1() { return cCorrectasAssignment_16_2_1; }
		
		//[Respuesta|EString]
		public CrossReference getCorrectasRespuestaCrossReference_16_2_1_0() { return cCorrectasRespuestaCrossReference_16_2_1_0; }
		
		//EString
		public RuleCall getCorrectasRespuestaEStringParserRuleCall_16_2_1_0_1() { return cCorrectasRespuestaEStringParserRuleCall_16_2_1_0_1; }
		
		//((isInicial?='isInicial')
		//'('
		//('siguientePreguntaAcierto:' siguientePreguntaAcierto=[Pregunta|EString])
		//(',')
		//('siguientePreguntaError:' siguientePreguntaError=[Pregunta|EString])
		//')')?
		public Group getGroup_17() { return cGroup_17; }
		
		//(isInicial?='isInicial')
		public Assignment getIsInicialAssignment_17_0() { return cIsInicialAssignment_17_0; }
		
		//'isInicial'
		public Keyword getIsInicialIsInicialKeyword_17_0_0() { return cIsInicialIsInicialKeyword_17_0_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_17_1() { return cLeftParenthesisKeyword_17_1; }
		
		//('siguientePreguntaAcierto:' siguientePreguntaAcierto=[Pregunta|EString])
		public Group getGroup_17_2() { return cGroup_17_2; }
		
		//'siguientePreguntaAcierto:'
		public Keyword getSiguientePreguntaAciertoKeyword_17_2_0() { return cSiguientePreguntaAciertoKeyword_17_2_0; }
		
		//siguientePreguntaAcierto=[Pregunta|EString]
		public Assignment getSiguientePreguntaAciertoAssignment_17_2_1() { return cSiguientePreguntaAciertoAssignment_17_2_1; }
		
		//[Pregunta|EString]
		public CrossReference getSiguientePreguntaAciertoPreguntaCrossReference_17_2_1_0() { return cSiguientePreguntaAciertoPreguntaCrossReference_17_2_1_0; }
		
		//EString
		public RuleCall getSiguientePreguntaAciertoPreguntaEStringParserRuleCall_17_2_1_0_1() { return cSiguientePreguntaAciertoPreguntaEStringParserRuleCall_17_2_1_0_1; }
		
		//(',')
		public Keyword getCommaKeyword_17_3() { return cCommaKeyword_17_3; }
		
		//('siguientePreguntaError:' siguientePreguntaError=[Pregunta|EString])
		public Group getGroup_17_4() { return cGroup_17_4; }
		
		//'siguientePreguntaError:'
		public Keyword getSiguientePreguntaErrorKeyword_17_4_0() { return cSiguientePreguntaErrorKeyword_17_4_0; }
		
		//siguientePreguntaError=[Pregunta|EString]
		public Assignment getSiguientePreguntaErrorAssignment_17_4_1() { return cSiguientePreguntaErrorAssignment_17_4_1; }
		
		//[Pregunta|EString]
		public CrossReference getSiguientePreguntaErrorPreguntaCrossReference_17_4_1_0() { return cSiguientePreguntaErrorPreguntaCrossReference_17_4_1_0; }
		
		//EString
		public RuleCall getSiguientePreguntaErrorPreguntaEStringParserRuleCall_17_4_1_0_1() { return cSiguientePreguntaErrorPreguntaEStringParserRuleCall_17_4_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_17_5() { return cRightParenthesisKeyword_17_5; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_18() { return cRightCurlyBracketKeyword_18; }
	}
	public class RespuestaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuestionario.Cuestionario.Respuesta");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameEStringParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cOpcionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cOpcionEStringParserRuleCall_2_0 = (RuleCall)cOpcionAssignment_2.eContents().get(0);
		
		//Respuesta returns Respuesta:
		//    name=EString ':' opcion=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//name=EString ':' opcion=EString
		public Group getGroup() { return cGroup; }
		
		//name=EString
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_0_0() { return cNameEStringParserRuleCall_0_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//opcion=EString
		public Assignment getOpcionAssignment_2() { return cOpcionAssignment_2; }
		
		//EString
		public RuleCall getOpcionEStringParserRuleCall_2_0() { return cOpcionEStringParserRuleCall_2_0; }
	}
	
	
	private final CuestionarioElements pCuestionario;
	private final PreguntaElements pPregunta;
	private final CategoriaElements pCategoria;
	private final EStringElements pEString;
	private final EDoubleElements pEDouble;
	private final EBooleanElements pEBoolean;
	private final PreguntaUnicaElements pPreguntaUnica;
	private final PreguntaMultipleElements pPreguntaMultiple;
	private final RespuestaElements pRespuesta;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public CuestionarioGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pCuestionario = new CuestionarioElements();
		this.pPregunta = new PreguntaElements();
		this.pCategoria = new CategoriaElements();
		this.pEString = new EStringElements();
		this.pEDouble = new EDoubleElements();
		this.pEBoolean = new EBooleanElements();
		this.pPreguntaUnica = new PreguntaUnicaElements();
		this.pPreguntaMultiple = new PreguntaMultipleElements();
		this.pRespuesta = new RespuestaElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("cuestionario.Cuestionario".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Cuestionario returns Cuestionario:
	//    'Cuestionario'
	//        'Preguntas:' preguntas+=Pregunta ( "," preguntas+=Pregunta)*
	//        'Categorias:' categorias+=Categoria ( "," categorias+=Categoria)*
	//        'Inicial:' preguntaInicial=[Pregunta|EString]
	//        'Finales:' preguntasFinales+=[Pregunta|EString] ( "," preguntasFinales+=[Pregunta|EString])* ;
	public CuestionarioElements getCuestionarioAccess() {
		return pCuestionario;
	}
	
	public ParserRule getCuestionarioRule() {
		return getCuestionarioAccess().getRule();
	}
	
	//Pregunta returns Pregunta:
	//    PreguntaUnica | PreguntaMultiple;
	public PreguntaElements getPreguntaAccess() {
		return pPregunta;
	}
	
	public ParserRule getPreguntaRule() {
		return getPreguntaAccess().getRule();
	}
	
	//Categoria returns Categoria:
	//    'categoria'
	//    name=EString
	//    '{'
	//        'dificultad' dificultad=EDouble
	//        ('SubCategorias:' subcategorias+=Categoria ( "," subcategorias+=Categoria)*)?
	//    '}';
	public CategoriaElements getCategoriaAccess() {
		return pCategoria;
	}
	
	public ParserRule getCategoriaRule() {
		return getCategoriaAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//EDouble returns ecore::EDouble:
	//    '-'? INT? '.' INT (('E'|'e') '-'? INT)?;
	public EDoubleElements getEDoubleAccess() {
		return pEDouble;
	}
	
	public ParserRule getEDoubleRule() {
		return getEDoubleAccess().getRule();
	}
	
	//EBoolean returns ecore::EBoolean:
	//    'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//PreguntaUnica returns PreguntaUnica:
	//    'pregUnica'
	//    name=EString
	//    '{'
	//        'Enunciado:' enunciado=EString
	//        'Respuestas' '{' respuestas+=Respuesta ( "," respuestas+=Respuesta)* '}'
	//        'Puntuacion:' puntuacion=EDouble
	//        'Penalizacion:' penalizacion=EDouble
	//        'Categoria:' categoria=[Categoria|EString]
	//        'Correcta:' correcta=[Respuesta|EString]
	//        ((isInicial?='isInicial')
	//        '('
	//        ('siguientePreguntaAcierto:' siguientePreguntaAcierto=[Pregunta|EString])
	//        (',')
	//        ('siguientePreguntaError:' siguientePreguntaError=[Pregunta|EString])
	//        ')')?
	//    '}';
	public PreguntaUnicaElements getPreguntaUnicaAccess() {
		return pPreguntaUnica;
	}
	
	public ParserRule getPreguntaUnicaRule() {
		return getPreguntaUnicaAccess().getRule();
	}
	
	//PreguntaMultiple returns PreguntaMultiple:
	//    'pregMultiple'
	//    name=EString
	//    '{'
	//        'Enunciado:' enunciado=EString
	//        'Respuestas' '{' respuestas+=Respuesta ( "," respuestas+=Respuesta)* '}'
	//        'Puntuacion:' puntuacion=EDouble
	//        'Penalizacion:' penalizacion=EDouble
	//        'Categoria:' categoria=[Categoria|EString]
	//        ('Correctas:' correctas+=[Respuesta|EString] ( "," correctas+=[Respuesta|EString])*)?
	//        ((isInicial?='isInicial')
	//        '('
	//        ('siguientePreguntaAcierto:' siguientePreguntaAcierto=[Pregunta|EString])
	//        (',')
	//        ('siguientePreguntaError:' siguientePreguntaError=[Pregunta|EString])
	//        ')')?
	//    '}';
	public PreguntaMultipleElements getPreguntaMultipleAccess() {
		return pPreguntaMultiple;
	}
	
	public ParserRule getPreguntaMultipleRule() {
		return getPreguntaMultipleAccess().getRule();
	}
	
	//Respuesta returns Respuesta:
	//    name=EString ':' opcion=EString;
	public RespuestaElements getRespuestaAccess() {
		return pRespuesta;
	}
	
	public ParserRule getRespuestaRule() {
		return getRespuestaAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
