/*
 * generated by Xtext 2.26.0
 */
package cuestionario.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class CuestionarioGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class CuestionarioElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuestionario.Cuestionario.Cuestionario");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCuestionarioKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cPreguntasKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPreguntasAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPreguntasPreguntaParserRuleCall_4_0 = (RuleCall)cPreguntasAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cPreguntasAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cPreguntasPreguntaParserRuleCall_5_1_0 = (RuleCall)cPreguntasAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cCategoriasKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cLeftCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cCategoriasAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cCategoriasCategoriaParserRuleCall_9_0 = (RuleCall)cCategoriasAssignment_9.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cCommaKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cCategoriasAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cCategoriasCategoriaParserRuleCall_10_1_0 = (RuleCall)cCategoriasAssignment_10_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cPreguntaInicialKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cPreguntaInicialAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final CrossReference cPreguntaInicialPreguntaCrossReference_13_0 = (CrossReference)cPreguntaInicialAssignment_13.eContents().get(0);
		private final RuleCall cPreguntaInicialPreguntaEStringParserRuleCall_13_0_1 = (RuleCall)cPreguntaInicialPreguntaCrossReference_13_0.eContents().get(1);
		private final Keyword cPreguntasFinalesKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Keyword cLeftParenthesisKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Assignment cPreguntasFinalesAssignment_16 = (Assignment)cGroup.eContents().get(16);
		private final CrossReference cPreguntasFinalesPreguntaCrossReference_16_0 = (CrossReference)cPreguntasFinalesAssignment_16.eContents().get(0);
		private final RuleCall cPreguntasFinalesPreguntaEStringParserRuleCall_16_0_1 = (RuleCall)cPreguntasFinalesPreguntaCrossReference_16_0.eContents().get(1);
		private final Group cGroup_17 = (Group)cGroup.eContents().get(17);
		private final Keyword cCommaKeyword_17_0 = (Keyword)cGroup_17.eContents().get(0);
		private final Assignment cPreguntasFinalesAssignment_17_1 = (Assignment)cGroup_17.eContents().get(1);
		private final CrossReference cPreguntasFinalesPreguntaCrossReference_17_1_0 = (CrossReference)cPreguntasFinalesAssignment_17_1.eContents().get(0);
		private final RuleCall cPreguntasFinalesPreguntaEStringParserRuleCall_17_1_0_1 = (RuleCall)cPreguntasFinalesPreguntaCrossReference_17_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_18 = (Keyword)cGroup.eContents().get(18);
		private final Keyword cRightCurlyBracketKeyword_19 = (Keyword)cGroup.eContents().get(19);
		
		//Cuestionario returns Cuestionario:
		//    'Cuestionario'
		//    '{'
		//        'preguntas' '{' preguntas+=Pregunta ( "," preguntas+=Pregunta)* '}'
		//        'categorias' '{' categorias+=Categoria ( "," categorias+=Categoria)* '}'
		//        'preguntaInicial' preguntaInicial=[Pregunta|EString]
		//        'preguntasFinales' '(' preguntasFinales+=[Pregunta|EString] ( "," preguntasFinales+=[Pregunta|EString])* ')'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Cuestionario'
		//'{'
		//    'preguntas' '{' preguntas+=Pregunta ( "," preguntas+=Pregunta)* '}'
		//    'categorias' '{' categorias+=Categoria ( "," categorias+=Categoria)* '}'
		//    'preguntaInicial' preguntaInicial=[Pregunta|EString]
		//    'preguntasFinales' '(' preguntasFinales+=[Pregunta|EString] ( "," preguntasFinales+=[Pregunta|EString])* ')'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Cuestionario'
		public Keyword getCuestionarioKeyword_0() { return cCuestionarioKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'preguntas'
		public Keyword getPreguntasKeyword_2() { return cPreguntasKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//preguntas+=Pregunta
		public Assignment getPreguntasAssignment_4() { return cPreguntasAssignment_4; }
		
		//Pregunta
		public RuleCall getPreguntasPreguntaParserRuleCall_4_0() { return cPreguntasPreguntaParserRuleCall_4_0; }
		
		//( "," preguntas+=Pregunta)*
		public Group getGroup_5() { return cGroup_5; }
		
		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }
		
		//preguntas+=Pregunta
		public Assignment getPreguntasAssignment_5_1() { return cPreguntasAssignment_5_1; }
		
		//Pregunta
		public RuleCall getPreguntasPreguntaParserRuleCall_5_1_0() { return cPreguntasPreguntaParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
		
		//'categorias'
		public Keyword getCategoriasKeyword_7() { return cCategoriasKeyword_7; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_8() { return cLeftCurlyBracketKeyword_8; }
		
		//categorias+=Categoria
		public Assignment getCategoriasAssignment_9() { return cCategoriasAssignment_9; }
		
		//Categoria
		public RuleCall getCategoriasCategoriaParserRuleCall_9_0() { return cCategoriasCategoriaParserRuleCall_9_0; }
		
		//( "," categorias+=Categoria)*
		public Group getGroup_10() { return cGroup_10; }
		
		//","
		public Keyword getCommaKeyword_10_0() { return cCommaKeyword_10_0; }
		
		//categorias+=Categoria
		public Assignment getCategoriasAssignment_10_1() { return cCategoriasAssignment_10_1; }
		
		//Categoria
		public RuleCall getCategoriasCategoriaParserRuleCall_10_1_0() { return cCategoriasCategoriaParserRuleCall_10_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
		
		//'preguntaInicial'
		public Keyword getPreguntaInicialKeyword_12() { return cPreguntaInicialKeyword_12; }
		
		//preguntaInicial=[Pregunta|EString]
		public Assignment getPreguntaInicialAssignment_13() { return cPreguntaInicialAssignment_13; }
		
		//[Pregunta|EString]
		public CrossReference getPreguntaInicialPreguntaCrossReference_13_0() { return cPreguntaInicialPreguntaCrossReference_13_0; }
		
		//EString
		public RuleCall getPreguntaInicialPreguntaEStringParserRuleCall_13_0_1() { return cPreguntaInicialPreguntaEStringParserRuleCall_13_0_1; }
		
		//'preguntasFinales'
		public Keyword getPreguntasFinalesKeyword_14() { return cPreguntasFinalesKeyword_14; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_15() { return cLeftParenthesisKeyword_15; }
		
		//preguntasFinales+=[Pregunta|EString]
		public Assignment getPreguntasFinalesAssignment_16() { return cPreguntasFinalesAssignment_16; }
		
		//[Pregunta|EString]
		public CrossReference getPreguntasFinalesPreguntaCrossReference_16_0() { return cPreguntasFinalesPreguntaCrossReference_16_0; }
		
		//EString
		public RuleCall getPreguntasFinalesPreguntaEStringParserRuleCall_16_0_1() { return cPreguntasFinalesPreguntaEStringParserRuleCall_16_0_1; }
		
		//( "," preguntasFinales+=[Pregunta|EString])*
		public Group getGroup_17() { return cGroup_17; }
		
		//","
		public Keyword getCommaKeyword_17_0() { return cCommaKeyword_17_0; }
		
		//preguntasFinales+=[Pregunta|EString]
		public Assignment getPreguntasFinalesAssignment_17_1() { return cPreguntasFinalesAssignment_17_1; }
		
		//[Pregunta|EString]
		public CrossReference getPreguntasFinalesPreguntaCrossReference_17_1_0() { return cPreguntasFinalesPreguntaCrossReference_17_1_0; }
		
		//EString
		public RuleCall getPreguntasFinalesPreguntaEStringParserRuleCall_17_1_0_1() { return cPreguntasFinalesPreguntaEStringParserRuleCall_17_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_18() { return cRightParenthesisKeyword_18; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_19() { return cRightCurlyBracketKeyword_19; }
	}
	public class PreguntaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuestionario.Cuestionario.Pregunta");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cPreguntaUnicaParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cPreguntaMultipleParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Pregunta returns Pregunta:
		//    PreguntaUnica | PreguntaMultiple;
		@Override public ParserRule getRule() { return rule; }
		
		//PreguntaUnica | PreguntaMultiple
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//PreguntaUnica
		public RuleCall getPreguntaUnicaParserRuleCall_0() { return cPreguntaUnicaParserRuleCall_0; }
		
		//PreguntaMultiple
		public RuleCall getPreguntaMultipleParserRuleCall_1() { return cPreguntaMultipleParserRuleCall_1; }
	}
	public class CategoriaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuestionario.Cuestionario.Categoria");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCategoriaKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cDificultadKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDificultadAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDificultadEDoubleParserRuleCall_4_0 = (RuleCall)cDificultadAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cSubcategoriasKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cSubcategoriasAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cSubcategoriasCategoriaParserRuleCall_5_2_0 = (RuleCall)cSubcategoriasAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cSubcategoriasAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cSubcategoriasCategoriaParserRuleCall_5_3_1_0 = (RuleCall)cSubcategoriasAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Categoria returns Categoria:
		//    'Categoria'
		//    name=EString
		//    '{'
		//        'dificultad' dificultad=EDouble
		//        ('subcategorias' '{' subcategorias+=Categoria ( "," subcategorias+=Categoria)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Categoria'
		//name=EString
		//'{'
		//    'dificultad' dificultad=EDouble
		//    ('subcategorias' '{' subcategorias+=Categoria ( "," subcategorias+=Categoria)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Categoria'
		public Keyword getCategoriaKeyword_0() { return cCategoriaKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'dificultad'
		public Keyword getDificultadKeyword_3() { return cDificultadKeyword_3; }
		
		//dificultad=EDouble
		public Assignment getDificultadAssignment_4() { return cDificultadAssignment_4; }
		
		//EDouble
		public RuleCall getDificultadEDoubleParserRuleCall_4_0() { return cDificultadEDoubleParserRuleCall_4_0; }
		
		//('subcategorias' '{' subcategorias+=Categoria ( "," subcategorias+=Categoria)* '}' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'subcategorias'
		public Keyword getSubcategoriasKeyword_5_0() { return cSubcategoriasKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//subcategorias+=Categoria
		public Assignment getSubcategoriasAssignment_5_2() { return cSubcategoriasAssignment_5_2; }
		
		//Categoria
		public RuleCall getSubcategoriasCategoriaParserRuleCall_5_2_0() { return cSubcategoriasCategoriaParserRuleCall_5_2_0; }
		
		//( "," subcategorias+=Categoria)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//subcategorias+=Categoria
		public Assignment getSubcategoriasAssignment_5_3_1() { return cSubcategoriasAssignment_5_3_1; }
		
		//Categoria
		public RuleCall getSubcategoriasCategoriaParserRuleCall_5_3_1_0() { return cSubcategoriasCategoriaParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuestionario.Cuestionario.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class EDoubleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuestionario.Cuestionario.EDouble");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EDouble returns ecore::EDouble:
		//    '-'? INT? '.' INT (('E'|'e') '-'? INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT? '.' INT (('E'|'e') '-'? INT)?
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
		
		//(('E'|'e') '-'? INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//('E'|'e')
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }
		
		//'E'
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }
		
		//'e'
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuestionario.Cuestionario.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//    'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class PreguntaUnicaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuestionario.Cuestionario.PreguntaUnica");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPreguntaUnicaKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cEnunciadoKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cEnunciadoAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cEnunciadoEStringParserRuleCall_4_0 = (RuleCall)cEnunciadoAssignment_4.eContents().get(0);
		private final Keyword cPuntuacionKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cPuntuacionAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cPuntuacionEDoubleParserRuleCall_6_0 = (RuleCall)cPuntuacionAssignment_6.eContents().get(0);
		private final Keyword cPenalizacionKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cPenalizacionAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cPenalizacionEDoubleParserRuleCall_8_0 = (RuleCall)cPenalizacionAssignment_8.eContents().get(0);
		private final Keyword cCategoriaKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cCategoriaAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final CrossReference cCategoriaCategoriaCrossReference_10_0 = (CrossReference)cCategoriaAssignment_10.eContents().get(0);
		private final RuleCall cCategoriaCategoriaEStringParserRuleCall_10_0_1 = (RuleCall)cCategoriaCategoriaCrossReference_10_0.eContents().get(1);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Assignment cIsInicialAssignment_11_0 = (Assignment)cGroup_11.eContents().get(0);
		private final Keyword cIsInicialIsInicialKeyword_11_0_0 = (Keyword)cIsInicialAssignment_11_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_11_1 = (Keyword)cGroup_11.eContents().get(1);
		private final Group cGroup_11_2 = (Group)cGroup_11.eContents().get(2);
		private final Keyword cSiguientePreguntaAciertoKeyword_11_2_0 = (Keyword)cGroup_11_2.eContents().get(0);
		private final Assignment cSiguientePreguntaAciertoAssignment_11_2_1 = (Assignment)cGroup_11_2.eContents().get(1);
		private final CrossReference cSiguientePreguntaAciertoPreguntaCrossReference_11_2_1_0 = (CrossReference)cSiguientePreguntaAciertoAssignment_11_2_1.eContents().get(0);
		private final RuleCall cSiguientePreguntaAciertoPreguntaEStringParserRuleCall_11_2_1_0_1 = (RuleCall)cSiguientePreguntaAciertoPreguntaCrossReference_11_2_1_0.eContents().get(1);
		private final Keyword cCommaKeyword_11_3 = (Keyword)cGroup_11.eContents().get(3);
		private final Group cGroup_11_4 = (Group)cGroup_11.eContents().get(4);
		private final Keyword cSiguientePreguntaErrorKeyword_11_4_0 = (Keyword)cGroup_11_4.eContents().get(0);
		private final Assignment cSiguientePreguntaErrorAssignment_11_4_1 = (Assignment)cGroup_11_4.eContents().get(1);
		private final CrossReference cSiguientePreguntaErrorPreguntaCrossReference_11_4_1_0 = (CrossReference)cSiguientePreguntaErrorAssignment_11_4_1.eContents().get(0);
		private final RuleCall cSiguientePreguntaErrorPreguntaEStringParserRuleCall_11_4_1_0_1 = (RuleCall)cSiguientePreguntaErrorPreguntaCrossReference_11_4_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_11_5 = (Keyword)cGroup_11.eContents().get(5);
		private final Keyword cRespuestasKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cLeftCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cRespuestasAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cRespuestasRespuestaParserRuleCall_14_0 = (RuleCall)cRespuestasAssignment_14.eContents().get(0);
		private final Group cGroup_15 = (Group)cGroup.eContents().get(15);
		private final Keyword cCommaKeyword_15_0 = (Keyword)cGroup_15.eContents().get(0);
		private final Assignment cRespuestasAssignment_15_1 = (Assignment)cGroup_15.eContents().get(1);
		private final RuleCall cRespuestasRespuestaParserRuleCall_15_1_0 = (RuleCall)cRespuestasAssignment_15_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Keyword cCorrectaKeyword_17 = (Keyword)cGroup.eContents().get(17);
		private final Assignment cCorrectaAssignment_18 = (Assignment)cGroup.eContents().get(18);
		private final CrossReference cCorrectaRespuestaCrossReference_18_0 = (CrossReference)cCorrectaAssignment_18.eContents().get(0);
		private final RuleCall cCorrectaRespuestaEStringParserRuleCall_18_0_1 = (RuleCall)cCorrectaRespuestaCrossReference_18_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_19 = (Keyword)cGroup.eContents().get(19);
		
		//PreguntaUnica returns PreguntaUnica:
		//    'PreguntaUnica'
		//    name=EString
		//    '{'
		//        'enunciado' enunciado=EString
		//        'puntuacion' puntuacion=EDouble
		//        'penalizacion' penalizacion=EDouble
		//        'categoria' categoria=[Categoria|EString]
		//        ((isInicial?='isInicial')
		//        '('
		//        ('siguientePreguntaAcierto' siguientePreguntaAcierto=[Pregunta|EString])
		//        (',')
		//        ('siguientePreguntaError' siguientePreguntaError=[Pregunta|EString])
		//        ')')?
		//        'respuestas' '{' respuestas+=Respuesta ( "," respuestas+=Respuesta)* '}'
		//        'correcta' correcta=[Respuesta|EString]
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'PreguntaUnica'
		//name=EString
		//'{'
		//    'enunciado' enunciado=EString
		//    'puntuacion' puntuacion=EDouble
		//    'penalizacion' penalizacion=EDouble
		//    'categoria' categoria=[Categoria|EString]
		//    ((isInicial?='isInicial')
		//    '('
		//    ('siguientePreguntaAcierto' siguientePreguntaAcierto=[Pregunta|EString])
		//    (',')
		//    ('siguientePreguntaError' siguientePreguntaError=[Pregunta|EString])
		//    ')')?
		//    'respuestas' '{' respuestas+=Respuesta ( "," respuestas+=Respuesta)* '}'
		//    'correcta' correcta=[Respuesta|EString]
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'PreguntaUnica'
		public Keyword getPreguntaUnicaKeyword_0() { return cPreguntaUnicaKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'enunciado'
		public Keyword getEnunciadoKeyword_3() { return cEnunciadoKeyword_3; }
		
		//enunciado=EString
		public Assignment getEnunciadoAssignment_4() { return cEnunciadoAssignment_4; }
		
		//EString
		public RuleCall getEnunciadoEStringParserRuleCall_4_0() { return cEnunciadoEStringParserRuleCall_4_0; }
		
		//'puntuacion'
		public Keyword getPuntuacionKeyword_5() { return cPuntuacionKeyword_5; }
		
		//puntuacion=EDouble
		public Assignment getPuntuacionAssignment_6() { return cPuntuacionAssignment_6; }
		
		//EDouble
		public RuleCall getPuntuacionEDoubleParserRuleCall_6_0() { return cPuntuacionEDoubleParserRuleCall_6_0; }
		
		//'penalizacion'
		public Keyword getPenalizacionKeyword_7() { return cPenalizacionKeyword_7; }
		
		//penalizacion=EDouble
		public Assignment getPenalizacionAssignment_8() { return cPenalizacionAssignment_8; }
		
		//EDouble
		public RuleCall getPenalizacionEDoubleParserRuleCall_8_0() { return cPenalizacionEDoubleParserRuleCall_8_0; }
		
		//'categoria'
		public Keyword getCategoriaKeyword_9() { return cCategoriaKeyword_9; }
		
		//categoria=[Categoria|EString]
		public Assignment getCategoriaAssignment_10() { return cCategoriaAssignment_10; }
		
		//[Categoria|EString]
		public CrossReference getCategoriaCategoriaCrossReference_10_0() { return cCategoriaCategoriaCrossReference_10_0; }
		
		//EString
		public RuleCall getCategoriaCategoriaEStringParserRuleCall_10_0_1() { return cCategoriaCategoriaEStringParserRuleCall_10_0_1; }
		
		//((isInicial?='isInicial')
		//'('
		//('siguientePreguntaAcierto' siguientePreguntaAcierto=[Pregunta|EString])
		//(',')
		//('siguientePreguntaError' siguientePreguntaError=[Pregunta|EString])
		//')')?
		public Group getGroup_11() { return cGroup_11; }
		
		//(isInicial?='isInicial')
		public Assignment getIsInicialAssignment_11_0() { return cIsInicialAssignment_11_0; }
		
		//'isInicial'
		public Keyword getIsInicialIsInicialKeyword_11_0_0() { return cIsInicialIsInicialKeyword_11_0_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_11_1() { return cLeftParenthesisKeyword_11_1; }
		
		//('siguientePreguntaAcierto' siguientePreguntaAcierto=[Pregunta|EString])
		public Group getGroup_11_2() { return cGroup_11_2; }
		
		//'siguientePreguntaAcierto'
		public Keyword getSiguientePreguntaAciertoKeyword_11_2_0() { return cSiguientePreguntaAciertoKeyword_11_2_0; }
		
		//siguientePreguntaAcierto=[Pregunta|EString]
		public Assignment getSiguientePreguntaAciertoAssignment_11_2_1() { return cSiguientePreguntaAciertoAssignment_11_2_1; }
		
		//[Pregunta|EString]
		public CrossReference getSiguientePreguntaAciertoPreguntaCrossReference_11_2_1_0() { return cSiguientePreguntaAciertoPreguntaCrossReference_11_2_1_0; }
		
		//EString
		public RuleCall getSiguientePreguntaAciertoPreguntaEStringParserRuleCall_11_2_1_0_1() { return cSiguientePreguntaAciertoPreguntaEStringParserRuleCall_11_2_1_0_1; }
		
		//(',')
		public Keyword getCommaKeyword_11_3() { return cCommaKeyword_11_3; }
		
		//('siguientePreguntaError' siguientePreguntaError=[Pregunta|EString])
		public Group getGroup_11_4() { return cGroup_11_4; }
		
		//'siguientePreguntaError'
		public Keyword getSiguientePreguntaErrorKeyword_11_4_0() { return cSiguientePreguntaErrorKeyword_11_4_0; }
		
		//siguientePreguntaError=[Pregunta|EString]
		public Assignment getSiguientePreguntaErrorAssignment_11_4_1() { return cSiguientePreguntaErrorAssignment_11_4_1; }
		
		//[Pregunta|EString]
		public CrossReference getSiguientePreguntaErrorPreguntaCrossReference_11_4_1_0() { return cSiguientePreguntaErrorPreguntaCrossReference_11_4_1_0; }
		
		//EString
		public RuleCall getSiguientePreguntaErrorPreguntaEStringParserRuleCall_11_4_1_0_1() { return cSiguientePreguntaErrorPreguntaEStringParserRuleCall_11_4_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_11_5() { return cRightParenthesisKeyword_11_5; }
		
		//'respuestas'
		public Keyword getRespuestasKeyword_12() { return cRespuestasKeyword_12; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_13() { return cLeftCurlyBracketKeyword_13; }
		
		//respuestas+=Respuesta
		public Assignment getRespuestasAssignment_14() { return cRespuestasAssignment_14; }
		
		//Respuesta
		public RuleCall getRespuestasRespuestaParserRuleCall_14_0() { return cRespuestasRespuestaParserRuleCall_14_0; }
		
		//( "," respuestas+=Respuesta)*
		public Group getGroup_15() { return cGroup_15; }
		
		//","
		public Keyword getCommaKeyword_15_0() { return cCommaKeyword_15_0; }
		
		//respuestas+=Respuesta
		public Assignment getRespuestasAssignment_15_1() { return cRespuestasAssignment_15_1; }
		
		//Respuesta
		public RuleCall getRespuestasRespuestaParserRuleCall_15_1_0() { return cRespuestasRespuestaParserRuleCall_15_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_16() { return cRightCurlyBracketKeyword_16; }
		
		//'correcta'
		public Keyword getCorrectaKeyword_17() { return cCorrectaKeyword_17; }
		
		//correcta=[Respuesta|EString]
		public Assignment getCorrectaAssignment_18() { return cCorrectaAssignment_18; }
		
		//[Respuesta|EString]
		public CrossReference getCorrectaRespuestaCrossReference_18_0() { return cCorrectaRespuestaCrossReference_18_0; }
		
		//EString
		public RuleCall getCorrectaRespuestaEStringParserRuleCall_18_0_1() { return cCorrectaRespuestaEStringParserRuleCall_18_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_19() { return cRightCurlyBracketKeyword_19; }
	}
	public class PreguntaMultipleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuestionario.Cuestionario.PreguntaMultiple");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPreguntaMultipleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cEnunciadoKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cEnunciadoAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cEnunciadoEStringParserRuleCall_4_0 = (RuleCall)cEnunciadoAssignment_4.eContents().get(0);
		private final Keyword cPuntuacionKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cPuntuacionAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cPuntuacionEDoubleParserRuleCall_6_0 = (RuleCall)cPuntuacionAssignment_6.eContents().get(0);
		private final Keyword cPenalizacionKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cPenalizacionAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cPenalizacionEDoubleParserRuleCall_8_0 = (RuleCall)cPenalizacionAssignment_8.eContents().get(0);
		private final Keyword cCategoriaKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cCategoriaAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final CrossReference cCategoriaCategoriaCrossReference_10_0 = (CrossReference)cCategoriaAssignment_10.eContents().get(0);
		private final RuleCall cCategoriaCategoriaEStringParserRuleCall_10_0_1 = (RuleCall)cCategoriaCategoriaCrossReference_10_0.eContents().get(1);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Assignment cIsInicialAssignment_11_0 = (Assignment)cGroup_11.eContents().get(0);
		private final Keyword cIsInicialIsInicialKeyword_11_0_0 = (Keyword)cIsInicialAssignment_11_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_11_1 = (Keyword)cGroup_11.eContents().get(1);
		private final Group cGroup_11_2 = (Group)cGroup_11.eContents().get(2);
		private final Keyword cSiguientePreguntaAciertoKeyword_11_2_0 = (Keyword)cGroup_11_2.eContents().get(0);
		private final Assignment cSiguientePreguntaAciertoAssignment_11_2_1 = (Assignment)cGroup_11_2.eContents().get(1);
		private final CrossReference cSiguientePreguntaAciertoPreguntaCrossReference_11_2_1_0 = (CrossReference)cSiguientePreguntaAciertoAssignment_11_2_1.eContents().get(0);
		private final RuleCall cSiguientePreguntaAciertoPreguntaEStringParserRuleCall_11_2_1_0_1 = (RuleCall)cSiguientePreguntaAciertoPreguntaCrossReference_11_2_1_0.eContents().get(1);
		private final Keyword cCommaKeyword_11_3 = (Keyword)cGroup_11.eContents().get(3);
		private final Group cGroup_11_4 = (Group)cGroup_11.eContents().get(4);
		private final Keyword cSiguientePreguntaErrorKeyword_11_4_0 = (Keyword)cGroup_11_4.eContents().get(0);
		private final Assignment cSiguientePreguntaErrorAssignment_11_4_1 = (Assignment)cGroup_11_4.eContents().get(1);
		private final CrossReference cSiguientePreguntaErrorPreguntaCrossReference_11_4_1_0 = (CrossReference)cSiguientePreguntaErrorAssignment_11_4_1.eContents().get(0);
		private final RuleCall cSiguientePreguntaErrorPreguntaEStringParserRuleCall_11_4_1_0_1 = (RuleCall)cSiguientePreguntaErrorPreguntaCrossReference_11_4_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_11_5 = (Keyword)cGroup_11.eContents().get(5);
		private final Keyword cRespuestasKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cLeftCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cRespuestasAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cRespuestasRespuestaParserRuleCall_14_0 = (RuleCall)cRespuestasAssignment_14.eContents().get(0);
		private final Group cGroup_15 = (Group)cGroup.eContents().get(15);
		private final Keyword cCommaKeyword_15_0 = (Keyword)cGroup_15.eContents().get(0);
		private final Assignment cRespuestasAssignment_15_1 = (Assignment)cGroup_15.eContents().get(1);
		private final RuleCall cRespuestasRespuestaParserRuleCall_15_1_0 = (RuleCall)cRespuestasAssignment_15_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Group cGroup_17 = (Group)cGroup.eContents().get(17);
		private final Keyword cCorrectasKeyword_17_0 = (Keyword)cGroup_17.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_17_1 = (Keyword)cGroup_17.eContents().get(1);
		private final Assignment cCorrectasAssignment_17_2 = (Assignment)cGroup_17.eContents().get(2);
		private final CrossReference cCorrectasRespuestaCrossReference_17_2_0 = (CrossReference)cCorrectasAssignment_17_2.eContents().get(0);
		private final RuleCall cCorrectasRespuestaEStringParserRuleCall_17_2_0_1 = (RuleCall)cCorrectasRespuestaCrossReference_17_2_0.eContents().get(1);
		private final Group cGroup_17_3 = (Group)cGroup_17.eContents().get(3);
		private final Keyword cCommaKeyword_17_3_0 = (Keyword)cGroup_17_3.eContents().get(0);
		private final Assignment cCorrectasAssignment_17_3_1 = (Assignment)cGroup_17_3.eContents().get(1);
		private final CrossReference cCorrectasRespuestaCrossReference_17_3_1_0 = (CrossReference)cCorrectasAssignment_17_3_1.eContents().get(0);
		private final RuleCall cCorrectasRespuestaEStringParserRuleCall_17_3_1_0_1 = (RuleCall)cCorrectasRespuestaCrossReference_17_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_17_4 = (Keyword)cGroup_17.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_18 = (Keyword)cGroup.eContents().get(18);
		
		//PreguntaMultiple returns PreguntaMultiple:
		//    'PreguntaMultiple'
		//    name=EString
		//    '{'
		//        'enunciado' enunciado=EString
		//        'puntuacion' puntuacion=EDouble
		//        'penalizacion' penalizacion=EDouble
		//        'categoria' categoria=[Categoria|EString]
		//        ((isInicial?='isInicial')
		//        '('
		//        ('siguientePreguntaAcierto' siguientePreguntaAcierto=[Pregunta|EString])
		//        (',')
		//        ('siguientePreguntaError' siguientePreguntaError=[Pregunta|EString])
		//        ')')?
		//        'respuestas' '{' respuestas+=Respuesta ( "," respuestas+=Respuesta)* '}'
		//        ('correctas' '(' correctas+=[Respuesta|EString] ( "," correctas+=[Respuesta|EString])* ')' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'PreguntaMultiple'
		//name=EString
		//'{'
		//    'enunciado' enunciado=EString
		//    'puntuacion' puntuacion=EDouble
		//    'penalizacion' penalizacion=EDouble
		//    'categoria' categoria=[Categoria|EString]
		//    ((isInicial?='isInicial')
		//    '('
		//    ('siguientePreguntaAcierto' siguientePreguntaAcierto=[Pregunta|EString])
		//    (',')
		//    ('siguientePreguntaError' siguientePreguntaError=[Pregunta|EString])
		//    ')')?
		//    'respuestas' '{' respuestas+=Respuesta ( "," respuestas+=Respuesta)* '}'
		//    ('correctas' '(' correctas+=[Respuesta|EString] ( "," correctas+=[Respuesta|EString])* ')' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'PreguntaMultiple'
		public Keyword getPreguntaMultipleKeyword_0() { return cPreguntaMultipleKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'enunciado'
		public Keyword getEnunciadoKeyword_3() { return cEnunciadoKeyword_3; }
		
		//enunciado=EString
		public Assignment getEnunciadoAssignment_4() { return cEnunciadoAssignment_4; }
		
		//EString
		public RuleCall getEnunciadoEStringParserRuleCall_4_0() { return cEnunciadoEStringParserRuleCall_4_0; }
		
		//'puntuacion'
		public Keyword getPuntuacionKeyword_5() { return cPuntuacionKeyword_5; }
		
		//puntuacion=EDouble
		public Assignment getPuntuacionAssignment_6() { return cPuntuacionAssignment_6; }
		
		//EDouble
		public RuleCall getPuntuacionEDoubleParserRuleCall_6_0() { return cPuntuacionEDoubleParserRuleCall_6_0; }
		
		//'penalizacion'
		public Keyword getPenalizacionKeyword_7() { return cPenalizacionKeyword_7; }
		
		//penalizacion=EDouble
		public Assignment getPenalizacionAssignment_8() { return cPenalizacionAssignment_8; }
		
		//EDouble
		public RuleCall getPenalizacionEDoubleParserRuleCall_8_0() { return cPenalizacionEDoubleParserRuleCall_8_0; }
		
		//'categoria'
		public Keyword getCategoriaKeyword_9() { return cCategoriaKeyword_9; }
		
		//categoria=[Categoria|EString]
		public Assignment getCategoriaAssignment_10() { return cCategoriaAssignment_10; }
		
		//[Categoria|EString]
		public CrossReference getCategoriaCategoriaCrossReference_10_0() { return cCategoriaCategoriaCrossReference_10_0; }
		
		//EString
		public RuleCall getCategoriaCategoriaEStringParserRuleCall_10_0_1() { return cCategoriaCategoriaEStringParserRuleCall_10_0_1; }
		
		//((isInicial?='isInicial')
		//'('
		//('siguientePreguntaAcierto' siguientePreguntaAcierto=[Pregunta|EString])
		//(',')
		//('siguientePreguntaError' siguientePreguntaError=[Pregunta|EString])
		//')')?
		public Group getGroup_11() { return cGroup_11; }
		
		//(isInicial?='isInicial')
		public Assignment getIsInicialAssignment_11_0() { return cIsInicialAssignment_11_0; }
		
		//'isInicial'
		public Keyword getIsInicialIsInicialKeyword_11_0_0() { return cIsInicialIsInicialKeyword_11_0_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_11_1() { return cLeftParenthesisKeyword_11_1; }
		
		//('siguientePreguntaAcierto' siguientePreguntaAcierto=[Pregunta|EString])
		public Group getGroup_11_2() { return cGroup_11_2; }
		
		//'siguientePreguntaAcierto'
		public Keyword getSiguientePreguntaAciertoKeyword_11_2_0() { return cSiguientePreguntaAciertoKeyword_11_2_0; }
		
		//siguientePreguntaAcierto=[Pregunta|EString]
		public Assignment getSiguientePreguntaAciertoAssignment_11_2_1() { return cSiguientePreguntaAciertoAssignment_11_2_1; }
		
		//[Pregunta|EString]
		public CrossReference getSiguientePreguntaAciertoPreguntaCrossReference_11_2_1_0() { return cSiguientePreguntaAciertoPreguntaCrossReference_11_2_1_0; }
		
		//EString
		public RuleCall getSiguientePreguntaAciertoPreguntaEStringParserRuleCall_11_2_1_0_1() { return cSiguientePreguntaAciertoPreguntaEStringParserRuleCall_11_2_1_0_1; }
		
		//(',')
		public Keyword getCommaKeyword_11_3() { return cCommaKeyword_11_3; }
		
		//('siguientePreguntaError' siguientePreguntaError=[Pregunta|EString])
		public Group getGroup_11_4() { return cGroup_11_4; }
		
		//'siguientePreguntaError'
		public Keyword getSiguientePreguntaErrorKeyword_11_4_0() { return cSiguientePreguntaErrorKeyword_11_4_0; }
		
		//siguientePreguntaError=[Pregunta|EString]
		public Assignment getSiguientePreguntaErrorAssignment_11_4_1() { return cSiguientePreguntaErrorAssignment_11_4_1; }
		
		//[Pregunta|EString]
		public CrossReference getSiguientePreguntaErrorPreguntaCrossReference_11_4_1_0() { return cSiguientePreguntaErrorPreguntaCrossReference_11_4_1_0; }
		
		//EString
		public RuleCall getSiguientePreguntaErrorPreguntaEStringParserRuleCall_11_4_1_0_1() { return cSiguientePreguntaErrorPreguntaEStringParserRuleCall_11_4_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_11_5() { return cRightParenthesisKeyword_11_5; }
		
		//'respuestas'
		public Keyword getRespuestasKeyword_12() { return cRespuestasKeyword_12; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_13() { return cLeftCurlyBracketKeyword_13; }
		
		//respuestas+=Respuesta
		public Assignment getRespuestasAssignment_14() { return cRespuestasAssignment_14; }
		
		//Respuesta
		public RuleCall getRespuestasRespuestaParserRuleCall_14_0() { return cRespuestasRespuestaParserRuleCall_14_0; }
		
		//( "," respuestas+=Respuesta)*
		public Group getGroup_15() { return cGroup_15; }
		
		//","
		public Keyword getCommaKeyword_15_0() { return cCommaKeyword_15_0; }
		
		//respuestas+=Respuesta
		public Assignment getRespuestasAssignment_15_1() { return cRespuestasAssignment_15_1; }
		
		//Respuesta
		public RuleCall getRespuestasRespuestaParserRuleCall_15_1_0() { return cRespuestasRespuestaParserRuleCall_15_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_16() { return cRightCurlyBracketKeyword_16; }
		
		//('correctas' '(' correctas+=[Respuesta|EString] ( "," correctas+=[Respuesta|EString])* ')' )?
		public Group getGroup_17() { return cGroup_17; }
		
		//'correctas'
		public Keyword getCorrectasKeyword_17_0() { return cCorrectasKeyword_17_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_17_1() { return cLeftParenthesisKeyword_17_1; }
		
		//correctas+=[Respuesta|EString]
		public Assignment getCorrectasAssignment_17_2() { return cCorrectasAssignment_17_2; }
		
		//[Respuesta|EString]
		public CrossReference getCorrectasRespuestaCrossReference_17_2_0() { return cCorrectasRespuestaCrossReference_17_2_0; }
		
		//EString
		public RuleCall getCorrectasRespuestaEStringParserRuleCall_17_2_0_1() { return cCorrectasRespuestaEStringParserRuleCall_17_2_0_1; }
		
		//( "," correctas+=[Respuesta|EString])*
		public Group getGroup_17_3() { return cGroup_17_3; }
		
		//","
		public Keyword getCommaKeyword_17_3_0() { return cCommaKeyword_17_3_0; }
		
		//correctas+=[Respuesta|EString]
		public Assignment getCorrectasAssignment_17_3_1() { return cCorrectasAssignment_17_3_1; }
		
		//[Respuesta|EString]
		public CrossReference getCorrectasRespuestaCrossReference_17_3_1_0() { return cCorrectasRespuestaCrossReference_17_3_1_0; }
		
		//EString
		public RuleCall getCorrectasRespuestaEStringParserRuleCall_17_3_1_0_1() { return cCorrectasRespuestaEStringParserRuleCall_17_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_17_4() { return cRightParenthesisKeyword_17_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_18() { return cRightCurlyBracketKeyword_18; }
	}
	public class RespuestaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuestionario.Cuestionario.Respuesta");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRespuestaKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cOpcionKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cOpcionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cOpcionEStringParserRuleCall_4_0 = (RuleCall)cOpcionAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Respuesta returns Respuesta:
		//    'Respuesta'
		//    name=EString
		//    '{'
		//        'opcion' opcion=EString
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Respuesta'
		//name=EString
		//'{'
		//    'opcion' opcion=EString
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Respuesta'
		public Keyword getRespuestaKeyword_0() { return cRespuestaKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'opcion'
		public Keyword getOpcionKeyword_3() { return cOpcionKeyword_3; }
		
		//opcion=EString
		public Assignment getOpcionAssignment_4() { return cOpcionAssignment_4; }
		
		//EString
		public RuleCall getOpcionEStringParserRuleCall_4_0() { return cOpcionEStringParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	
	
	private final CuestionarioElements pCuestionario;
	private final PreguntaElements pPregunta;
	private final CategoriaElements pCategoria;
	private final EStringElements pEString;
	private final EDoubleElements pEDouble;
	private final EBooleanElements pEBoolean;
	private final PreguntaUnicaElements pPreguntaUnica;
	private final PreguntaMultipleElements pPreguntaMultiple;
	private final RespuestaElements pRespuesta;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public CuestionarioGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pCuestionario = new CuestionarioElements();
		this.pPregunta = new PreguntaElements();
		this.pCategoria = new CategoriaElements();
		this.pEString = new EStringElements();
		this.pEDouble = new EDoubleElements();
		this.pEBoolean = new EBooleanElements();
		this.pPreguntaUnica = new PreguntaUnicaElements();
		this.pPreguntaMultiple = new PreguntaMultipleElements();
		this.pRespuesta = new RespuestaElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("cuestionario.Cuestionario".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Cuestionario returns Cuestionario:
	//    'Cuestionario'
	//    '{'
	//        'preguntas' '{' preguntas+=Pregunta ( "," preguntas+=Pregunta)* '}'
	//        'categorias' '{' categorias+=Categoria ( "," categorias+=Categoria)* '}'
	//        'preguntaInicial' preguntaInicial=[Pregunta|EString]
	//        'preguntasFinales' '(' preguntasFinales+=[Pregunta|EString] ( "," preguntasFinales+=[Pregunta|EString])* ')'
	//    '}';
	public CuestionarioElements getCuestionarioAccess() {
		return pCuestionario;
	}
	
	public ParserRule getCuestionarioRule() {
		return getCuestionarioAccess().getRule();
	}
	
	//Pregunta returns Pregunta:
	//    PreguntaUnica | PreguntaMultiple;
	public PreguntaElements getPreguntaAccess() {
		return pPregunta;
	}
	
	public ParserRule getPreguntaRule() {
		return getPreguntaAccess().getRule();
	}
	
	//Categoria returns Categoria:
	//    'Categoria'
	//    name=EString
	//    '{'
	//        'dificultad' dificultad=EDouble
	//        ('subcategorias' '{' subcategorias+=Categoria ( "," subcategorias+=Categoria)* '}' )?
	//    '}';
	public CategoriaElements getCategoriaAccess() {
		return pCategoria;
	}
	
	public ParserRule getCategoriaRule() {
		return getCategoriaAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//EDouble returns ecore::EDouble:
	//    '-'? INT? '.' INT (('E'|'e') '-'? INT)?;
	public EDoubleElements getEDoubleAccess() {
		return pEDouble;
	}
	
	public ParserRule getEDoubleRule() {
		return getEDoubleAccess().getRule();
	}
	
	//EBoolean returns ecore::EBoolean:
	//    'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//PreguntaUnica returns PreguntaUnica:
	//    'PreguntaUnica'
	//    name=EString
	//    '{'
	//        'enunciado' enunciado=EString
	//        'puntuacion' puntuacion=EDouble
	//        'penalizacion' penalizacion=EDouble
	//        'categoria' categoria=[Categoria|EString]
	//        ((isInicial?='isInicial')
	//        '('
	//        ('siguientePreguntaAcierto' siguientePreguntaAcierto=[Pregunta|EString])
	//        (',')
	//        ('siguientePreguntaError' siguientePreguntaError=[Pregunta|EString])
	//        ')')?
	//        'respuestas' '{' respuestas+=Respuesta ( "," respuestas+=Respuesta)* '}'
	//        'correcta' correcta=[Respuesta|EString]
	//    '}';
	public PreguntaUnicaElements getPreguntaUnicaAccess() {
		return pPreguntaUnica;
	}
	
	public ParserRule getPreguntaUnicaRule() {
		return getPreguntaUnicaAccess().getRule();
	}
	
	//PreguntaMultiple returns PreguntaMultiple:
	//    'PreguntaMultiple'
	//    name=EString
	//    '{'
	//        'enunciado' enunciado=EString
	//        'puntuacion' puntuacion=EDouble
	//        'penalizacion' penalizacion=EDouble
	//        'categoria' categoria=[Categoria|EString]
	//        ((isInicial?='isInicial')
	//        '('
	//        ('siguientePreguntaAcierto' siguientePreguntaAcierto=[Pregunta|EString])
	//        (',')
	//        ('siguientePreguntaError' siguientePreguntaError=[Pregunta|EString])
	//        ')')?
	//        'respuestas' '{' respuestas+=Respuesta ( "," respuestas+=Respuesta)* '}'
	//        ('correctas' '(' correctas+=[Respuesta|EString] ( "," correctas+=[Respuesta|EString])* ')' )?
	//    '}';
	public PreguntaMultipleElements getPreguntaMultipleAccess() {
		return pPreguntaMultiple;
	}
	
	public ParserRule getPreguntaMultipleRule() {
		return getPreguntaMultipleAccess().getRule();
	}
	
	//Respuesta returns Respuesta:
	//    'Respuesta'
	//    name=EString
	//    '{'
	//        'opcion' opcion=EString
	//    '}';
	public RespuestaElements getRespuestaAccess() {
		return pRespuesta;
	}
	
	public ParserRule getRespuestaRule() {
		return getRespuestaAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
