<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="redes_transporte_publico" nsURI="redes_transporte_publico" nsPrefix="redes_transporte_publico">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="RedTransporte">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="lineasParadasConsecutivasIguales"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="lineasParadasConsecutivasIguales" value="&#xA;&#x9;&#x9;&#x9;linea->forAll(linea1, linea2 | &#xA;&#x9;&#x9;&#x9;&#x9;linea1.parada->forAll(par1|&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;linea2.parada->forAll(par2|&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;(par1 = par2) implies (&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;linea2.parada->forAll(par3|&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;linea1.parada->forAll(par4|&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;par3 = par4 and (linea1.parada->indexOf(par4) = 1 + linea1.parada->indexOf(par1)) and (linea2.parada->indexOf(par2) = 1 + linea2.parada->indexOf(par3))&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;implies(linea1.siquienteParadaDistancia[par1] = linea2.siquienteParadaDistancia[par2])&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;)&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;)&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;)&#xA;&#x9;&#x9;&#x9;&#x9;)&#xA;&#x9;&#x9;&#x9;)&#xA;&#x9;&#x9;&#x9;)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linea" lowerBound="1" upperBound="-1"
        eType="#//Linea" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parada" lowerBound="2"
        upperBound="-1" eType="#//Parada" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Metro" eSuperTypes="#//Linea">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nonDuplicateColores nonDuplicateCodigoMetro"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="nonDuplicateColores" value="&#xA;&#x9;&#x9;Metro.allInstances()->isUnique(color)"/>
      <details key="nonDuplicateCodigoMetro" value="&#xA;&#x9;&#x9;Metro.allInstances()->isUnique(codigo)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paradas: Parada"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//Colores"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bus" eSuperTypes="#//Linea">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nonDuplicateCodigoBus"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="nonDuplicateCodigoBus" value="&#xA;&#x9;&#x9;Bus.allInstances()->isUnique(codigo)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paradas: Parada"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diurnas" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nocturnas" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tren" eSuperTypes="#//Linea">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nonDuplicateCodigoTren"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="nonDuplicateCodigoTren" value="&#xA;&#x9;&#x9;Tren.allInstances()->isUnique(codigo)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paradas: Parada"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parada">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nonDuplicatedNombreParada"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="nonDuplicatedNombreParada" value="&#xA;&#x9;&#x9;Parada.allInstances()->isUnique(nombre)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accesible" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bicicletas" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aparcamientoGrat" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="asesos" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transbordo" eType="#//Transbordos"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Linea" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parada" lowerBound="2"
        upperBound="-1" eType="#//Parada"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="horaApertura" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="horaCierre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="descuento" upperBound="-1"
        eType="#//Descuento" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="siguienteParadaDistancia"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap" transient="true"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="siguienteParadaTiempo"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Colores">
    <eLiterals name="Rojo"/>
    <eLiterals name="Verde" value="1"/>
    <eLiterals name="Azul" value="2"/>
    <eLiterals name="Amarillo" value="3"/>
    <eLiterals name="Negro" value="4"/>
    <eLiterals name="Blanco" value="5" literal="Blanno"/>
    <eLiterals name="Morado" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Transbordos">
    <eLiterals name="Corto"/>
    <eLiterals name="Largo" value="1"/>
    <eLiterals name="NoPermitido" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ZonaTarificacion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enumeracion" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tarifaBus" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tarifaMetro" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tarifaTren" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Descuento">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="horaApertura" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="horaCierre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descuento" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral=""/>
  </eClassifiers>
</ecore:EPackage>
