/*
 * generated by Xtext 2.26.0
 */
package cuestionario.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CuestionarioUiModule extends AbstractCuestionarioUiModule {

	public CuestionarioUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
